scripts/user-luxmark3: do not crash on kernel build failure
Instead of:

Thread 1 "luxmark" received signal SIGSEGV, Segmentation fault.
0x0000555555a25b52 in luxrays::OpenCLIntersectionDevice::Stop (this=0x7fffb800b810) at LuxCore/src/luxrays/idevices/openclidevice.cpp:307
307		delete kernels;

It doesn't crash and may even display why the kernel didn't built:

[LuxRays] [7.510] [OpenCL device::AMD Radeon R9 390 Series (hawaii, LLVM 16.0.0, DRM 3.42, 5.15.0-50-generic)Intersect] QBVH compilation error: fatal error: cannot open file 'share/clc/hawaii-amdgcn-mesa-mesa3d.bc': Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM16.0.0git' Reader: 'LLVM 16.0.0git')
OpenCL ERROR: clBuildProgram(-11)